name: blueray_test_project
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  device_preview_plus: ^2.1.5
  dio: ^5.7.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_riverpod: ^2.6.1
  flutter_secure_storage: ^9.2.2
  freezed_annotation: ^2.4.4
  google_fonts: ^6.2.1
  json_annotation: ^4.9.0
  lottie: ^3.1.3
  otp_text_field: ^1.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.13
  freezed: ^2.5.7
  json_serializable: ^6.9.0

flutter:
  assets:
    - .env
    - assets/svgs/
    - assets/images/
    - assets/lotties/
  uses-material-design: true
